sudo: false
language: go
go:
  - 1.7rc5
  - 1.6.3
  - 1.5
install:
  - go get -u github.com/Masterminds/glide
  - glide install
env:
  - SCALA_VERSION=2.11 KAFKA_VERSION=0.9.0.1 GO15VENDOREXPERIMENT=1
  - SCALA_VERSION=2.11 KAFKA_VERSION=0.10.0.0 GO15VENDOREXPERIMENT=1
script:
  - make default test-race
